# kafka config
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id:
        ups: user-profile-submission-consumer-dev-1
        upv: user-profile-validation-result-consumer-dev-1
      max.poll.records: 50
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    user:
      profile:
        submission:
          topic: user-profile-submission-dev-1
        validation:
          result:
            topic: user-profile-validation-result-dev-1

# cache config
cache:
  lookup:
    timeout: 5000
  memcache:
    servers: localhost:11211
  timeout: 864000
  exception:
    threshold:
      timeout: 10
  mute:
    exception: false
  key:
    separator: ":"

# Actuator configs
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Resilience4j configs
resilience4j:
  circuitbreaker:
    instances:
      validateEndpoint:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

# Set the logging level for various packages and classes
logging:
  level:
    root: INFO
    org.springframework: INFO
